services:
  - type: web
    name: dafnehita
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_EMAILJS_SERVICE_ID
        sync: false
      - key: VITE_EMAILJS_TEMPLATE_ID
        sync: false
      - key: VITE_EMAILJS_PUBLIC_KEY
        sync: false
